default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root

development:
  <<: *default
  database: offers_app_development

test:
  <<: *default
  database: offers_app_test

production:
  <<: *default
  database: offers_app_production
  username: offers_app
  password: <%= ENV['offers_app_DATABASE_PASSWORD'] %>
